
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luthfi RZ
 */
public class futama extends javax.swing.JFrame {

    /**
     * Creates new form futama
     */
    public futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        labelnama = new javax.swing.JLabel();
        btntekan = new javax.swing.JButton();
        label_nim = new javax.swing.JLabel();
        ubahbtn = new javax.swing.JButton();
        label_kelas = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemograman Provis");
        setResizable(false);

        labelnama.setForeground(new java.awt.Color(255, 0, 0));
        labelnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnama.setText("HALLO WORLD");
        labelnama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btntekan.setText("Tekan Saya");
        btntekan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntekanMouseClicked(evt);
            }
        });
        btntekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntekanActionPerformed(evt);
            }
        });

        label_nim.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_nim.setForeground(new java.awt.Color(174, 70, 0));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nim.setText("NIM");
        label_nim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_nimMouseClicked(evt);
            }
        });

        ubahbtn.setText("Click");
        ubahbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahbtnMouseClicked(evt);
            }
        });
        ubahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahbtnActionPerformed(evt);
            }
        });

        label_kelas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_kelas.setForeground(new java.awt.Color(174, 70, 0));
        label_kelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_kelas.setText("KELAS");
        label_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_kelasMouseClicked(evt);
            }
        });

        label_nama.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_nama.setForeground(new java.awt.Color(174, 70, 0));
        label_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nama.setText("NAMA");
        label_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_namaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_nim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(ubahbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btntekan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(labelnama)
                .addGap(18, 18, 18)
                .addComponent(btntekan)
                .addGap(18, 18, 18)
                .addComponent(label_nim)
                .addGap(7, 7, 7)
                .addComponent(label_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_kelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ubahbtn)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntekanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntekanMouseClicked
        // TODO add your handling code here:
        labelnama.setText("Hallo Nama Saya Muhammad Abdurrohman");
        JOptionPane.showMessageDialog(null,"Selamat Anda Berhasil Menghubah Label Nama");
    }//GEN-LAST:event_btntekanMouseClicked

    private void btntekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntekanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntekanActionPerformed

    private void ubahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahbtnActionPerformed

    private void label_nimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_nimMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_nimMouseClicked

    private void ubahbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahbtnMouseClicked
        // TODO add your handling code here:
        label_nim.setText("10118342");
        label_nama.setText("Muhammad Abdurrohman");
        label_kelas.setText("IF-8");
        JOptionPane.showMessageDialog(null,"Identitas Anda Berhasil diubah");
    }//GEN-LAST:event_ubahbtnMouseClicked

    private void label_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_kelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_kelasMouseClicked

    private void label_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_namaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_namaMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntekan;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel label_kelas;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel labelnama;
    private javax.swing.JButton ubahbtn;
    // End of variables declaration//GEN-END:variables
}
